### ISSUE TITLE
Is there a way to use non ANSI keys ?

### ISSUE THREAD

**Issue by Ambroisie** [kiibohd/KiiConf#4]
I'm using an AZERTY ISO layout at the moment, and would like to configure my keyboard to use that without writing and compiling my own BIOS, is there a way to use ISO keys ?

**Comment by haata** [comment]
It depends on what sort of keys you need. If they are provided by US ANSI, then it's easy.

However, the USB HID Spec assumes that the OS will take care of the US ANSI to AZERTY ISO conversion.
Someday I'll write a driver or daemon that can output unicode directly, but that is quite a ways off.

**Comment by Ambroisie** [comment]
Well obviously if I'm asking, it means I want to use non US ANSI keys... Could you tell me more about this USB HID thingy ?

Thanks anyways, looking forward to an even better kll inplementation and infinty keyboards :D

**Comment by haata** [comment]
There are two main spec documents that are a good read on this.

The main spec http://www.usb.org/developers/hidpage/HID1_11.pdf. This one is more about how HID itself works than specifically keymappings.

This is the one you'll likely be interested in (Section 10)
http://www.usb.org/developers/hidpage/Hut1_12v2.pdf

One thing I haven't done a lot of research into yet is the HID LANGIDs. If the OS is setup correctly, it should be possible to indicate to the OS as soon as the keyboard is plugged in, that it's an AZERTY keyboard instead of a US ANSI one (the default). The hope is that the OS localization/internationalization settings will take over and do the right thing. LANGIDs is Section 3.6.

**Comment by Ambroisie** [comment]
I'm gonna believe you on this one, I can't really read that at the moment. If I understood correctly it should mean that even so the layout is ANSI US, if my system (Windows at the moment) is well setup, it should be used just like an AZERTY but in ANSI 104 key (60%) style ?

**Comment by haata** [comment]
Yep, that's how it works. You just need to know what the US ANSI key is for
the corresponding AZERTY key and it should just work.

**Comment by Ambroisie** [comment]
So how should I go to configure that in say Windows 8.1 ? Isn't it already configured by Microsoft ?

**Comment by haata** [comment]
The way I like to think about it. Take a standard US ANSI keyboard layout
https://mdn.mozillademos.org/files/3374/KB_United_States.svg

By default the keyboard should just work if you set the keyboard to AZERTY
in windows. Though you may need to remap some of the extra keys that don't
exist on US ANSI.

**Comment by haata** [comment]
I've tried to capture this bug in the wiki. Hopefully you've managed to configure the layout successfully.
